config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :farmers
  root :to => 'welcome#index'
  get '/register' => 'farmers#new', :as => :register

  get '/login' => 'sessions#new', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
  post '/sessions/create' => 'sessions#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farmer.rb
class Farmer < ActiveRecord::Base
  #attr_accessor :email, :farm, :name, :produce, :produce_price, :wepay_access_token, :wepay_account_id, :password

  validates :password, :presence => true
  validates :password, :length => { :in => 6..200}
  validates :name, :email, :presence => true
  validates :email, :uniqueness => { :case_sensitive => false }
  validates :email, :format => { :with => /@/, :message => " is invalid" }

  def password
    password_hash ? @password ||= BCrypt::Password.new(password_hash) : nil
  end

  def password=(new_password)
    @password = BCrypt::Password.create(new_password)
    self.password_hash = @password
  end

  def self.authenticate(email, test_password)
    farmer = Farmer.find_by_email(email)
    if farmer && farmer.password == test_password
      farmer
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    @current_user ||= Farmer.find(session[:farmer_id]) if session[:farmer_id]
  rescue ActiveRecord::RecordNotFound
    session[:farmer_id] = nil
  end

end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  before_action :set_farmer, only: [:show, :edit, :update, :destroy]
  before_action :check_auth, only: [:edit, :update, :destroy]

  # GET /farmers
  # GET /farmers.json
  def index
    @farmers = Farmer.all
  end

  # GET /farmers/1
  def show
    @is_admin = current_user && current_user.id == @farmer.id
  end

  # GET /farmers/new
  def new
    if current_user
      redirect_to root_path, :notice => "You are already registered"
    end
    @farmer = Farmer.new
  end

  # GET /farmers/1/edit
  def edit
    check_auth
  end

  # POST /farmers
  # POST /farmers.json
  def create
    @farmer = Farmer.new(farmer_params)

    if @farmer.save
      session[:farmer_id] = @farmer.id
      redirect_to @farmer, notice: "Farmer was successfully created."
    else
      render action: "new"
    end

=begin
    respond_to do |format|
      if @farmer.save
        format.html { redirect_to @farmer, notice: 'Farmer was successfully created.'}
        format.json { render :show, status: :created, location: @farmer }
      else
        format.html { render :new }
        format.json { render json: @farmer.errors, status: :unprocessable_entity }
      end
    end
=end

  end

  # PATCH/PUT /farmers/1
  # PATCH/PUT /farmers/1.json
  def update
    respond_to do |format|
      if @farmer.update(farmer_params)
        format.html { redirect_to @farmer, notice: "Farmer was successfully updated." }
        format.json { render :show, status: :ok, location: @farmer }
      else
        format.html { render :edit }
        format.json { render json: @farmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farmers/1
  # DELETE /farmers/1.json
  def destroy
    check_auth
    @farmer.destroy
    respond_to do |format|
      format.html { redirect_to farmers_url, notice: "Farmer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_farmer
    @farmer = Farmer.find(params[:id])
  end

  # Check Authentication
  def check_auth
    if current_user.nil? || current_user.id != @farmer.id
      redirect_to @farmer, notice: "You are not allowed to edit!"
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def farmer_params
    params.require(:farmer).permit(:name, :email, :password, :farm, :produce, :produce_price)#, :wepay_access_token, :wepay_account_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /sessions/new
  def new
  end

# POST /sessions
  def create
    farmer = Farmer.authenticate params[:email], params[:password]
    if farmer
      session[:farmer_id] = farmer.id
      redirect_to farmer, :notice => "Welcome back to WeFarm"
    else
      redirect_to :login, :alert => "Invalid email or password"
    end
  end

  def destroy
    session[:farmer_id] = nil
    redirect_to root_path :notice => "You have been logged out"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/farmers/_form.html.erb
<%= form_for(@farmer) do |f| %>
  <% if @farmer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@farmer.errors.count, "error") %> prohibited this farmer from being saved:</h2>

      <ul>
        <% @farmer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :farm %>
    <%= f.text_field :farm %>
  </div>
  <div class="field">
    <%= f.label :produce %>
    <%= f.text_field :produce %>
  </div>
  <div class="field">
    <%= f.label :produce_price %>
    <%= f.number_field :produce_price %>
  </div>
  <div class="actions">
    <%= f.submit(:class  => "btn btn-primary") %>
  </div>
<% end %>

app/views/farmers/edit.html.erb
<h1>Editing Farmer</h1>

<%= render 'form', farmer: @farmer %>

<%= link_to 'Show', @farmer %> |
<%= link_to 'Back', farmers_path %>

app/views/farmers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Farmers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <!--
      <th>Password hash</th>
      -->
      <th>Farm</th>
      <th>Produce</th>
      <th>Price</th>
      <!--
      <th>Wepay access token</th>
      <th>Wepay account</th>
      -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @farmers.each do |farmer| %>
      <tr>
        <td><%= farmer.name %></td>
        <td><%= farmer.email %></td>
        <!--
        <td><%= farmer.password_hash %></td>
        -->
        <td><%= farmer.farm %></td>
        <td><%= farmer.produce %></td>
        <td><%= farmer.produce_price %></td>
        <!--
        <td><%= farmer.wepay_access_token %></td>
        <td><%= farmer.wepay_account_id %></td>
        -->
        <td><%= link_to 'Show', farmer %></td>
        <td><%= link_to 'Edit', edit_farmer_path(farmer) %></td>
        <td><%= link_to 'Destroy', farmer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% if @farmers.size == 0 %>
        <em>No Tweets Found</em>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Farmer', new_farmer_path %>

app/views/farmers/new.html.erb
<h1>New Farmer</h1>

<%= render 'form', farmer: @farmer %>

<%= link_to 'Back', farmers_path %>

app/views/farmers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @farmer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @farmer.email %>
</p>

<!--
<p>
  <strong>Password hash:</strong>
  <%= @farmer.password_hash %>
</p>
-->
<p>
  <strong>Farm:</strong>
  <%= @farmer.farm %>
</p>

<p>
  <strong>Produce:</strong>
  <%= @farmer.produce %>
</p>

<p>
  <strong>Produce price:</strong>
  <%= @farmer.produce_price %>
</p>

<!--
<p>
  <strong>Wepay access token:</strong>
  <%= @farmer.wepay_access_token %>
</p>

<p>
  <strong>Wepay account:</strong>
  <%= @farmer.wepay_account_id %>
</p>
-->
<% if (@is_admin) %>
  <%= link_to 'Edit', edit_farmer_path(@farmer) %>
<% end %>

<%= link_to 'Back', farmers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeFarm</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Farmers', farmers_path, :class => 'brand' %>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <% if current_user %>
            <li>
              <%= link_to 'Logout', logout_path %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Register', register_path %>
            </li>
            <li>
              <%= link_to 'Login', login_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">

  <div class="row-fluid">
    <div class="span8">
      <% if flash.notice %>
        <div class="alert alert-block alert-info">
          <button type="button" class="close" data-dismiss="alert">×
            <%= flash.notice %>
          </button>
        </div>
      <% end %>
      <% if flash.alert %>
        <div class="alert alert-block alert-error">
          <button type="button" class="close" data-dismiss="alert">×
            <%= flash.alert %>
          </button>
        </div>
      <% end %>
    </div>
  </div>

  <%= yield %>

</div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to WeFarm</h1>
<p>You can buy a lots of fresh and local farm-to-fork produce here. If you
  are a farmer and want to sell your produce, please register.</p>